version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mechcontrol-admin
      POSTGRES_PASSWORD: mechcontrol-admin161829
      POSTGRES_DB: mechcontrol
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev"]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: mechcontrol
      DB_USER: mechcontrol-admin
      DB_PASSWORD: mechcontrol-admin161829
      KEYCLOAK_ADMIN: mechcontrol-admin
      KEYCLOAK_ADMIN_PASSWORD: mechcontrol-admin161829
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  mechcontrol-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - keycloak
      - redis
    ports:
      - "5678:5678"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Redis: "redis:6379"
    networks:
      - default

volumes:
  postgres_data:
  keycloak_data:

networks:
  default:
