version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  mech-control-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5678:5678"
      - "5679:5679"
      - "9229:9229" 
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    networks:
      - default
    labels:
      com.jetbrains.rider.fast.mode: "false"
      com.jetbrains.rider.debugger.port: "9229"
      com.jetbrains.rider.debugger.enabled: "true"
      com.jetbrains.rider.run-docker: "true"

volumes:
  postgres_data:
  keycloak_data:

networks:
  default:
